[project]
name = "evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks-agents>=1.8.2",
    "jupyter>=1.1.1",
    "mlflow[databricks]>=3.6.0",
    "notebook>=7.4.7",
]
